---
# tasks file for exim

  - name: yum install exim
    yum: 
      name: exim
      state: latest
  - name: exim conf
    copy:
      src: files/exim.conf
      dest: /etc/exim/exim.conf
      owner: root
      group: root
      mode: 0644
